services:
  db:
    image: postgres:15
    container_name: postgres-midterm
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feedback_hub
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  seed:
    build: ./backend
    depends_on:
      - db
    env_file:
      ./backend/.env.docker
    command: sh -c "npx prisma db push && npm run seed"
  
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - db
      - redis
    expose:
      - "5000"
    env_file:
      - ./backend/.env.docker
    deploy:
      replicas: 3

  nginx:
    image: nginx:latest
    container_name: nginx-loadbalancer
    depends_on:
      - backend
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  frontend:
    build: ./frontend
    container_name: vite-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
  redis_data:
